### ISSUE TITLE
are you interested in freelancing

### ISSUE THREAD

**Issue by seekingdeep** [juexinwang/GRGNN#2]
@juexinwang 
hi there,
i have a task that i want to solve.
are you interested in freelancing.
if so, then what is your email so i can contact you
waiting for your reply

**Comment by juexinwang** [comment]
Hi, just noticed this issue.
Let me know what is your task.
wang.juexin(at)gmail.com

**Comment by seekingdeep** [comment]
i sent you an email, have a look
